title: SlavaBuchnev
theme: minima

# Дополнительные поля
author:  Buchnev Vyacheslav

# Социальные сети
github_username:  SlavaBuchnev

# порядок страниц
header_pages:
  - about.md
  - projects.md
  - posts.md

collections:
  projects:
    output: true
    permalink: /projects/:path/